-- TERMINAL 1

BEGIN TRANSACTION ISOLATION LEVEL REPEATABLE READ;
SELECT SUM(rating) FROM pizzeria;
SELECT SUM(rating) FROM pizzeria;
COMMIT;

-- TERMINAL 2

BEGIN TRANSACTION ISOLATION LEVEL REPEATABLE READ;
INSERT INTO pizzeria VALUES (
    11,
    'Kazan pizza 1',
    5
);
COMMIT;

