-- TERMINAL 1

BEGIN ISOLATION LEVEL REPEATABLE READ;
SHOW TRANSACTION ISOLATION LEVEL;

UPDATE pizzeria SET rating = 4 WHERE name = 'Pizza Hut';
COMMIT;


-- TERMINAL 2

BEGIN ISOLATION LEVEL REPEATABLE READ;
SHOW TRANSACTION ISOLATION LEVEL;

UPDATE pizzeria SET rating = 3.6 WHERE name = 'Pizza Hut';
COMMIT;

